#define FUCKING_SHIT unsigned int

#include "CNetObject.hpp"

struct CPlayer : public CNetObject {
    FUCKING_SHIT peer;
    irr::core::array<short, irr::core::irrAllocator<short> > stats;
    FUCKING_SHIT info;
    irr::u8 oldteam;
    bool isBot;
    bool isLocal;
    FUCKING_SHIT controls;
    bool bCustomControls;
    bool fakepeer;
    irr::s16 pingInTicks;
    CBadassPtr<FUCKING_SHIT> actor;
    bool joingameafterconnect;
    irr::core::vector3df playercolor;
    float playerpitch;
    FUCKING_SHIT teammenu;
    bool changedteams;
    FUCKING_SHIT gamemenu;
    FUCKING_SHIT respawnmenu;
    FUCKING_SHIT pickedspawn;
    unsigned int randomspawn;
    bool beginplay;
    FUCKING_SHIT lastrequestactor;
    FUCKING_SHIT auth;
    String oldname;
    CBadassPtr<FUCKING_SHIT> chatText;
    irr::core::position2di actorpos2d;
    irr::core::array<FUCKING_SHIT, irr::core::irrAllocator<FUCKING_SHIT> > badasspointers;
    int playtime;
    int teamplaytime;
    int lastignoredchattime;
    irr::u32 hardwareid;
    int maxping_warnings;
    int hack_warnings;
    int recdBuild_warnings;
    int speedhack_warnings;
    bool tobe_kicked;
    bool votedon;
    int kick_time;
    int kick_reason;
    int kick_delay;
    Vec2f lastdeathpos;
    irr::core::array<unsigned int, irr::core::irrAllocator<unsigned int> > ticks_griefer;
    irr::core::array<int, irr::core::irrAllocator<int> > ticks_griefer_time;
    bool freeze;
    bool authed_with_username;
    CBadassPtr<FUCKING_SHIT> party_owner;
    int party_index;
  public:
    CPlayer(const irr::c8 *);
	CPlayer(ENetPeer *);
    ~CPlayer();
    void Create(void);
    virtual void Send_Delta(FUCKING_SHIT, FUCKING_SHIT, FUCKING_SHIT);
    virtual bool Receive_Delta(FUCKING_SHIT &, FUCKING_SHIT, FUCKING_SHIT, bool &);
    virtual void Send_CreateData(FUCKING_SHIT);
    virtual bool Receive_CreateData(FUCKING_SHIT, bool);
    virtual bool Kill(void);
    virtual void DoTick(void);
    virtual void setNetworkID(short int);
    void SetPeer(FUCKING_SHIT);
    void ResetStats(void);
    bool customHeadsCheck(void);
    FUCKING_SHIT getControls(void);
    void setControls(FUCKING_SHIT);
    void setPingInTicks(irr::s16);
    void onActorDie(FUCKING_SHIT);
    void onActorRespawnReady(FUCKING_SHIT);
    void ClientRespawn(void);
    void onJoinServer(void);
    void ShowTeamMenu(void);
    void DestroyTeamMenu(void);
    void ChangeTeam(int);
    int CallbackTeamPick(void);
    void ShowGameMenu(bool, bool);
    void DestroyGameMenu(void);
    void CloseAllGameMenus(void);
    int CallbackGameMainMenu(void);
    int CallbackGamePlayer(void);
    int CallbackGameTeam(void);
    int CallbackGameClass(void);
    int CallbackGameJoinGame(void);
    int CallbackGameRespawn(void);
    int CallbackGameVote(void);
    void ShowRespawnMenu(void);
    void DestroyRespawnMenu(void);
    int CallbackRespawnPrev(void);
    int CallbackRespawnRandom(void);
    int CallbackRespawnNext(void);
    void AddPoints(int, bool);
    void AddKills(int);
    void AddDeaths(int);
    virtual void Chat(const wchar_t *, irr::video::SColor, irr::video::SColor);
    void ReleaseBP(FUCKING_SHIT);
    void AddBP(FUCKING_SHIT);
    void NullBP(void);
    bool tickedGriefer(FUCKING_SHIT);
    bool addGriefer(FUCKING_SHIT);
    bool removeGriefer(FUCKING_SHIT);
    void CheckGrieferKick(int);
	bool isMod(void);
};
