struct CClass {
    int index;
    CRules *rules;
    CTeam *team;
    irr::s32 actorcache;
    irr::s32 inventorycache;
    irr::f32 default_health;
    irr::f32 default_armor;
    WideString name;
    WideString tool;
    irr::u16 actor_sprite_size;
    irr::u16 actor_heads_size;
    String actor_name;
    String actor_config;
    String actor_sprite_male;
    String actor_sprite_female;
    String actor_heads_male;
    String actor_heads_female;
    irr::u8 stone_default;
    irr::u8 wood_default;
    irr::u8 gold_default;
    irr::u8 arrows_default;
    irr::u8 bombs_default;
    irr::u8 stone_warmup;
    irr::u8 wood_warmup;
    irr::u8 gold_warmup;
    irr::u8 arrows_warmup;
    irr::u8 bombs_warmup;
    bool allowed_at_tent;
    irr::f32 knockback_scale;
    irr::video::ITexture *sprite_male;
    irr::video::ITexture *sprite_female;
    irr::video::ITexture *heads_male;
    irr::video::ITexture *heads_female;
    irr::video::ITexture *emblem;
    String emblemfile;
    irr::core::array<HeadOffset, irr::core::irrAllocator<HeadOffset> > male_head_offsets;
    irr::core::array<HeadOffset, irr::core::irrAllocator<HeadOffset> > female_head_offsets;
    irr::u8 max_zoom_out;
    irr::f32 zoom_level_1;
    irr::f32 zoom_level_2;
    irr::f32 zoom_level_3;
  public:
    CClass(int, CRules *, CTeam *);
    ~CClass(int);
    bool Unserialize(CBitStream &);
    bool Serialize(CBitStream &);
    void Load(void);
}
